/**
 * @file /js/constants.js
 * @description System-wide immutable constants, event enumerations, and 
 * configuration boundaries for the EDGE V6 operating system.
 * Acts as the semantic vocabulary across all engines and UI components.
 * @version 6.0.0
 * @module constants
 */

/**
 * Global Event Bus Event Typologies.
 * Used for decentralized pub/sub communication across decoupled modules.
 * @readonly
 * @enum {string}
 */
export const SYSTEM_EVENTS = Object.freeze({
    // --- Lifecycle & System Events ---
    BOOTSTRAP_COMPLETE: 'system:bootstrap_complete',
    SERVICE_WORKER_REGISTERED: 'system:sw_registered',
    
    // --- Data Stream & Network Events ---
    WS_CONNECTED: 'network:ws_connected',
    WS_DISCONNECTED: 'network:ws_disconnected',
    WS_ERROR: 'network:ws_error',
    API_RATE_LIMIT_EXCEEDED: 'network:api_rate_limit',
    
    // --- Market Engine Events ---
    MARKET_DATA_TICK: 'market:tick',
    MARKET_DATA_STALE: 'market:stale',
    MARKET_REGIME_UPDATED: 'market:regime_updated',
    
    // --- Alpha & Quantitative Events ---
    ALPHA_MATRIX_UPDATED: 'alpha:matrix_updated',
    BEST_TRADE_IDENTIFIED: 'alpha:best_trade_identified',
    RISK_RADAR_ALERT: 'alpha:risk_radar_alert',
    
    // --- Portfolio & Journal Events ---
    CAPITAL_ALLOCATION_COMPUTED: 'portfolio:allocation_computed',
    TRADE_EXECUTED: 'journal:trade_executed',
    JOURNAL_SYNCED: 'journal:synced',
    
    // --- UI & Interaction Events ---
    VIEW_CHANGED: 'ui:view_changed',
    NOTIFICATION_DISPATCHED: 'ui:notification_dispatched',
    THEME_TOGGLED: 'ui:theme_toggled'
});

/**
 * Recognized Structural Market Regimes.
 * Dictates execution speed, risk multipliers, and hold durations.
 * @readonly
 * @enum {string}
 */
export const MARKET_REGIMES = Object.freeze({
    TREND_EXPANSION: 'TREND_EXPANSION',
    TREND_EXHAUSTION: 'TREND_EXHAUSTION',
    COMPRESSION_SQUEEZE: 'COMPRESSION_SQUEEZE',
    CHOP_MATRIX: 'CHOP_MATRIX',
    LIQUIDATION_CASCADE: 'LIQUIDATION_CASCADE',
    PRICE_DISCOVERY: 'PRICE_DISCOVERY'
});

/**
 * Standardized Default Asset Universe for scanning.
 * Optimizes websocket subscription density.
 * @readonly
 * @type {string[]}
 */
export const DEFAULT_ASSET_UNIVERSE = Object.freeze([
    'BTC-USDT-SWAP',
    'ETH-USDT-SWAP',
    'SOL-USDT-SWAP',
    'AVAX-USDT-SWAP',
    'DOGE-USDT-SWAP',
    'XRP-USDT-SWAP',
    'LINK-USDT-SWAP',
    'ARB-USDT-SWAP',
    'OP-USDT-SWAP',
    'INJ-USDT-SWAP'
]);

/**
 * Application View Routing Identifiers.
 * @readonly
 * @enum {string}
 */
export const VIEWS = Object.freeze({
    HOME: 'home',
    HOTLIST: 'hotlist',
    MARKET: 'market',
    JOURNAL: 'journal',
    SETTINGS: 'settings'
});

/**
 * Time and Performance scheduling boundaries (in milliseconds).
 * Used for debouncing, throttling, and frame calculations.
 * @readonly
 * @enum {number}
 */
export const TIMING = Object.freeze({
    FRAME_120HZ: 8,             // ~8.33ms per frame
    FRAME_60HZ: 16,             // ~16.66ms per frame
    THROTTLE_UI_UPDATE: 250,    // 4 updates per second max for high-density components
    STALE_DATA_THRESHOLD: 5000, // 5 seconds before data is marked dead
    TOAST_DURATION: 3500        // Notification display length
});

/**
 * Actionable recommendation typologies generated by the Alpha Engine.
 * @readonly
 * @enum {string}
 */
export const TRADE_DIRECTIONS = Object.freeze({
    LONG: 'LONG',
    SHORT: 'SHORT',
    STAY_IN_CASH: 'STAY_IN_CASH',
    AVOID: 'AVOID'
});

/**
 * Storage Keys for IndexedDB and LocalStorage layers.
 * @readonly
 * @enum {string}
 */
export const STORAGE_KEYS = Object.freeze({
    USER_SETTINGS: 'edge_v6_settings',
    JOURNAL_DATABASE: 'edge_v6_journal',
    MARKET_CACHE: 'edge_v6_market_cache'
});
